### ISSUE TITLE
2-tier vs 3-tier network

### ISSUE THREAD

**Issue by mshindo** [SystemsApproach/sdn#16]
In Chapter 2, there's a paragraph "A datacenter switching fabric is a network often designed according to a leaf-spine topology. The basic idea is illustrated by the small 4-rack/3-tier example shown in Figure 8. Each rack has a Top-of-Rack (ToR) switch that interconnects the servers in that rack; these are referred to as the leaf switches of the fabric. (There are typically two such ToR switches per rack for resilience, but the figure shows only one for simplicity.) Each leaf switch then connects to a subset of available spine switches, with two requirements: (1) that there be multiple paths between any pair of racks, and (2) that each rack-to-rack path is two-hops (i.e., via a single intermediate spine switch). Note that this means in 3-tier design like the one shown in Figure 9, every server-to-server path is either two hops (server-leaf-server in the intra-rack case) or four hops (server-leaf-spine-leaf-server in the inter-rack case)."

I think calling this leaf-spine network a "3-tier" is a bit confusing. It may mean that it is "server-leaf-spine" hence called 3-tier but I don't think it is common usage. Also, a 3-tier network often means the traditional "core/distribution/access" network, which also contributes to further confusion.

**Comment by llpeterson** [comment]
You're right. That should be two-tier. Thanks for this and the other typos
you flagged. --Larry

**Comment by drbruced12** [comment]
I have made an edit to the appropriate text, removing any discussion of tiers, as 3-tier is definitely used to mean something else, and 2-tier isn't in common use in this context.
