### ISSUE TITLE
netvirt: "realized state arrow" not in the figure "fig-three-planes".

### ISSUE THREAD

**Issue by ebiken** [SystemsApproach/sdn#20]
In netvirt.rst 8.2.2 Management, Control, and Data Planes, "... as indicated by the realized state arrow."

Looks like "realized state" does not appear in the diagram 'fig-three-planes'. From the context, it looks like the "realized state arrow" should be at the same location as "Control Directives". Maybe the diagram and/or sentence should be updated?

**Comment by llpeterson** [comment]
Good catch. I'll fix that. --Larry

**Comment by drbruced12** [comment]
Resolved in commit 76d346a6267
