### ISSUE TITLE
sentence mentioning there are 8 chapters while it's now 10.

### ISSUE THREAD

**Issue by ebiken** [SystemsApproach/sdn#32]
https://github.com/SystemsApproach/sdn/blob/dde3b7f8a7ad3d9ef5e55378d7eccfda3d451297/exercises.rst?plain=1#L169

> That there are 8 exercises and 8 chapters is a coincidence.

I think this sentence was not updated when number of chapter increased from 8 to 10.
(FYI: In Japanese edition, I simply removed this sentence)

**Comment by drbruced12** [comment]
Thanks for raising this. It is now fixed in commit 025d980
