### ISSUE TITLE
A typo in chapter 4, switch.rst

### ISSUE THREAD

**Issue by fshahinfar1** [SystemsApproach/sdn#33]
Hi, thanks for the book.

I think there is a typo in `switch.rst` line 720 col 26.

The original text is:

    **bit** it's not until you add ``switch.p4`` that you have the functionality that runs in those stages. 

I guess "bit" should be "But".

**Comment by sinaebrahimi** [comment]
Interestingly, I corrected this typo in my recent pull request.
https://github.com/SystemsApproach/sdn/pull/34

**Comment by drbruced12** [comment]
Thanks to both of you.
